from __future__ import annotations

import os
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import quote_plus

from app.core.config import get_settings


@dataclass(frozen=True)
class RuntimeConfig:
    database_url: str | None = None
    database_source: str = "environment"
    updated_at: str | None = None


def runtime_config_path() -> Path:
    settings = get_settings()
    return Path(os.getenv("EOX_RUNTIME_CONFIG_FILE", settings.data_dir / ".eox_runtime.env"))


def env_export_path() -> Path:
    settings = get_settings()
    return Path(os.getenv("EOX_ENV_EXPORT_FILE", settings.data_dir / ".env.local"))


def _parse_env_file(path: Path) -> dict[str, str]:
    output: dict[str, str] = {}
    if not path.exists():
        return output
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        output[key.strip()] = value.strip().strip('"').strip("'")
    return output


def read_runtime_config() -> RuntimeConfig:
    values = _parse_env_file(runtime_config_path())
    database_url = values.get("EOX_DATABASE_URL") or values.get("DATABASE_URL")
    if not database_url:
        return RuntimeConfig()
    return RuntimeConfig(
        database_url=database_url,
        database_source=values.get("EOX_DATABASE_SOURCE") or "runtime-env-file",
        updated_at=values.get("EOX_DATABASE_UPDATED_AT"),
    )


def write_runtime_database_url(database_url: str, *, write_env_file: bool = True) -> RuntimeConfig:
    path = runtime_config_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    updated_at = datetime.now(timezone.utc).isoformat()
    content = (
        "# Generated by Cisco EOX Manager setup UI.\n"
        "EOX_DATABASE_SOURCE=runtime-env-file\n"
        f"EOX_DATABASE_UPDATED_AT={updated_at}\n"
        f"EOX_DATABASE_URL={database_url}\n"
    )
    path.write_text(content, encoding="utf-8")
    if write_env_file:
        write_env_export(database_url)
    return read_runtime_config()


def write_env_export(database_url: str) -> Path:
    path = env_export_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "# Generated by Cisco EOX Manager setup UI.\n"
        "# Docker Compose still needs a restart to consume this file directly.\n"
        f"EOX_DATABASE_URL={database_url}\n",
        encoding="utf-8",
    )
    return path


def effective_database_url() -> str:
    runtime = read_runtime_config()
    if runtime.database_url:
        return runtime.database_url
    return get_settings().database_url


def database_url_hint(value: str | None = None) -> str:
    url = value or effective_database_url()
    if not url:
        return ""
    masked = url
    if "://" in masked and "@" in masked:
        scheme, rest = masked.split("://", 1)
        credentials, host = rest.split("@", 1)
        if ":" in credentials:
            user, _password = credentials.split(":", 1)
            masked = f"{scheme}://{user}:****@{host}"
    return masked


def build_postgres_url(*, host: str, port: int, database: str, username: str, password: str) -> str:
    safe_user = quote_plus(username)
    safe_password = quote_plus(password)
    safe_host = host.strip() or "postgres"
    safe_database = database.strip() or "eox_cache"
    safe_port = int(port or 5432)
    return f"postgresql+psycopg://{safe_user}:{safe_password}@{safe_host}:{safe_port}/{safe_database}"


def build_sqlite_url(*, path: str | None = None) -> str:
    settings = get_settings()
    raw_path = (path or "").strip()
    sqlite_path = Path(raw_path).expanduser() if raw_path else settings.data_dir / "eox_dev.db"
    if not sqlite_path.is_absolute():
        sqlite_path = settings.data_dir / sqlite_path
    sqlite_path.parent.mkdir(parents=True, exist_ok=True)
    return f"sqlite:///{sqlite_path.as_posix()}"
