from __future__ import annotations

import hashlib
import hmac
import os
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable, Literal

from fastapi import HTTPException, Request, status
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.responses import JSONResponse

from app.core.config import get_settings

TokenRole = Literal["admin", "read"]


@dataclass(frozen=True)
class AuthStatus:
    enabled: bool
    admin_token_configured: bool
    read_token_configured: bool
    token_configured: bool
    required: bool
    source: str
    bootstrap_open: bool
    updated_at: str | None = None
    env_forced_enabled: bool = False


PROTECTED_PREFIXES = (
    "/api/eox",
    "/api/setup",
    "/api/logs",
    "/api/export",
    "/api/autopop",
    "/api/system",
    "/graphql",
)

OPEN_PATHS = (
    "/api/auth/status",
    "/api/auth/security-status",
    "/api/auth/bootstrap",
    "/api/auth/verify",
    "/api/setup/status",
    "/api/health",
    "/health",
    "/docs",
    "/redoc",
    "/openapi.json",
)

READ_POST_PATHS = (
    "/api/eox/lookup",
    "/graphql",
)

ADMIN_PREFIXES = (
    "/api/setup",
    "/api/auth",
    "/api/logs/frontend",
    "/api/system/maintenance",
    "/api/system/backups",
)


def auth_config_path() -> Path:
    settings = get_settings()
    return Path(os.getenv("EOX_AUTH_CONFIG_FILE", settings.data_dir / ".eox_auth.env"))


def _parse_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def _write_env_file(path: Path, values: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Generated by Cisco EOX Manager security setup UI."]
    for key, value in values.items():
        lines.append(f"{key}={value}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _hash_token(token: str) -> str:
    return hashlib.sha256(token.encode("utf-8")).hexdigest()


def _env_truthy(value: str | None) -> bool:
    return (value or "").strip().lower() in {"1", "true", "yes", "on"}


def _configured_hashes() -> tuple[str | None, str | None, str, str | None]:
    admin_hash = os.getenv("EOX_ADMIN_TOKEN_HASH")
    read_hash = os.getenv("EOX_READ_TOKEN_HASH")
    source = "environment-hash" if admin_hash or read_hash else "not-configured"
    updated_at = None

    if os.getenv("EOX_ADMIN_TOKEN"):
        admin_hash = _hash_token(os.getenv("EOX_ADMIN_TOKEN", ""))
        source = "environment-token"
    if os.getenv("EOX_READ_TOKEN"):
        read_hash = _hash_token(os.getenv("EOX_READ_TOKEN", ""))
        source = "environment-token"

    path = auth_config_path()
    values = _parse_env_file(path)
    if values.get("EOX_ADMIN_TOKEN_HASH") or values.get("EOX_READ_TOKEN_HASH"):
        admin_hash = admin_hash or values.get("EOX_ADMIN_TOKEN_HASH")
        read_hash = read_hash or values.get("EOX_READ_TOKEN_HASH")
        source = "runtime-auth-file"
        updated_at = values.get("EOX_AUTH_UPDATED_AT")

    return admin_hash, read_hash, source, updated_at


def auth_enabled() -> bool:
    if _env_truthy(os.getenv("EOX_AUTH_ENABLED")):
        return True
    values = _parse_env_file(auth_config_path())
    return _env_truthy(values.get("EOX_AUTH_ENABLED"))


def get_auth_status() -> AuthStatus:
    admin_hash, read_hash, source, updated_at = _configured_hashes()
    enabled = auth_enabled()
    admin_configured = bool(admin_hash)
    read_configured = bool(read_hash)
    token_configured = admin_configured or read_configured
    bootstrap_open = enabled and not admin_configured
    return AuthStatus(
        enabled=enabled,
        admin_token_configured=admin_configured,
        read_token_configured=read_configured,
        token_configured=token_configured,
        required=enabled and token_configured,
        source=source,
        bootstrap_open=bootstrap_open,
        updated_at=updated_at,
        env_forced_enabled=_env_truthy(os.getenv("EOX_AUTH_ENABLED")),
    )


def _save_token_hash(*, token: str, role: TokenRole, enable_auth: bool | None = None) -> AuthStatus:
    clean = (token or "").strip()
    if len(clean) < 12:
        raise ValueError(f"{role.title()} token must be at least 12 characters long")
    path = auth_config_path()
    values = _parse_env_file(path)
    values["EOX_AUTH_UPDATED_AT"] = datetime.now(timezone.utc).isoformat()
    if enable_auth is not None:
        values["EOX_AUTH_ENABLED"] = "true" if enable_auth else "false"
    elif "EOX_AUTH_ENABLED" not in values:
        values["EOX_AUTH_ENABLED"] = "true"
    key = "EOX_ADMIN_TOKEN_HASH" if role == "admin" else "EOX_READ_TOKEN_HASH"
    values[key] = _hash_token(clean)
    _write_env_file(path, values)
    return get_auth_status()


def save_admin_token(token: str, *, enable_auth: bool = True) -> AuthStatus:
    return _save_token_hash(token=token, role="admin", enable_auth=enable_auth)


def save_read_token(token: str, *, enable_auth: bool | None = None) -> AuthStatus:
    return _save_token_hash(token=token, role="read", enable_auth=enable_auth)


def set_runtime_auth_enabled(enabled: bool) -> AuthStatus:
    path = auth_config_path()
    values = _parse_env_file(path)
    values["EOX_AUTH_UPDATED_AT"] = datetime.now(timezone.utc).isoformat()
    values["EOX_AUTH_ENABLED"] = "true" if enabled else "false"
    _write_env_file(path, values)
    return get_auth_status()


def extract_token(request: Request) -> str | None:
    auth_header = request.headers.get("authorization") or ""
    if auth_header.lower().startswith("bearer "):
        return auth_header.split(" ", 1)[1].strip()
    return (
        request.headers.get("x-eox-admin-token")
        or request.headers.get("x-eox-read-token")
        or request.headers.get("x-eox-api-token")
        or None
    )


def token_role(token: str | None) -> TokenRole | None:
    status_data = get_auth_status()
    if not status_data.enabled:
        return "admin"
    admin_hash, read_hash, _source, _updated_at = _configured_hashes()
    if not admin_hash and not read_hash:
        return "admin"
    if not token:
        return None
    token_hash = _hash_token(token.strip())
    if admin_hash and hmac.compare_digest(token_hash, admin_hash):
        return "admin"
    if read_hash and hmac.compare_digest(token_hash, read_hash):
        return "read"
    return None


def verify_token(token: str | None) -> bool:
    return token_role(token) is not None


def is_open_path(path: str, open_paths: Iterable[str] = OPEN_PATHS) -> bool:
    return any(path == item or path.startswith(f"{item}/") for item in open_paths)


def is_protected_path(path: str, protected_prefixes: Iterable[str] = PROTECTED_PREFIXES) -> bool:
    return any(path == item or path.startswith(f"{item}/") for item in protected_prefixes)


def _is_admin_required(path: str, method: str) -> bool:
    if path.startswith("/api/autopop") and method.upper() != "GET":
        return True
    if path.startswith("/api/export") and method.upper() not in {"GET", "HEAD"}:
        return True
    if any(path == item or path.startswith(f"{item}/") for item in ADMIN_PREFIXES):
        return True
    if method.upper() in {"POST", "PUT", "PATCH", "DELETE"} and path not in READ_POST_PATHS:
        return True
    return False


def has_permission(role: TokenRole | None, path: str, method: str) -> bool:
    if role == "admin":
        return True
    if role == "read":
        if _is_admin_required(path, method):
            return False
        return method.upper() in {"GET", "HEAD"} or path in READ_POST_PATHS
    return False


async def require_admin(request: Request) -> None:
    if token_role(extract_token(request)) != "admin":
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Admin token required")


class AdminAuthMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request: Request, call_next):
        if request.method == "OPTIONS":
            return await call_next(request)
        path = request.url.path
        if is_open_path(path) or not is_protected_path(path):
            return await call_next(request)
        role = token_role(extract_token(request))
        if has_permission(role, path, request.method):
            response = await call_next(request)
            if role:
                response.headers.setdefault("X-EOX-Token-Role", role)
            return response
        required = "admin" if _is_admin_required(path, request.method) else "read or admin"
        return JSONResponse(
            {
                "detail": f"{required.title()} token required. Send Authorization: Bearer <token>.",
                "auth_required": True,
                "required_role": required,
            },
            status_code=status.HTTP_401_UNAUTHORIZED,
        )
